"""
Enterprise Knowledge Base API — FastAPI application entry point.

Start with:
    uvicorn doc_service.main:app --reload
"""

from fastapi import FastAPI

from doc_service.api.routes_documents import router as documents_router
from doc_service.api.routes_health import router as health_router
from doc_service.core.config import settings

app = FastAPI(
    title="Enterprise Knowledge Base API",
    description=(
        "API service layer for the Enterprise Knowledge Base POC. "
        "Provides access to OKF documents generated by the document import pipeline."
    ),
    version=settings.version,
)

# Register routers
app.include_router(health_router, tags=["Health"])
app.include_router(documents_router, tags=["Documents"])
